In [1]:
import pandas as pd

In [2]:
data1 = {
    'Zone': ['West', 'South', 'West', 'North', 'East', 'South'],
    'Person': ['Jack', 'Jane', 'Jill', 'Jason', 'Jordan', 'Jenna'],
    'Division': ['Sales', 'Marketing', 'Sales', 'Operations', 'Admin', 'Sales']
}

df1 = pd.DataFrame(data1)

In [3]:
data2 = {
    'Region'  : ['West', 'East', 'West', 'North', 'East', 'Midwest'],
    'Person'  : ['Jack', 'Jackson', 'Jill', 'Jason', 'Jordan', 'Adam'],
    'Division': ['Sales', 'Management', 'Sales', 'Operations', 'Admin', 'Admin']
}

df2 = pd.DataFrame(data2)

In [4]:
df1

    Zone  Person    Division
0   West    Jack       Sales
1  South    Jane   Marketing
2   West    Jill       Sales
3  North   Jason  Operations
4   East  Jordan       Admin
5  South   Jenna       Sales

In [5]:
df2

    Region   Person    Division
0     West     Jack       Sales
1     East  Jackson  Management
2     West     Jill       Sales
3    North    Jason  Operations
4     East   Jordan       Admin
5  Midwest     Adam       Admin

In [7]:
df1.merge(df2)

    Zone  Person    Division Region
0   West    Jack       Sales   West
1   West    Jill       Sales   West
2  North   Jason  Operations  North
3   East  Jordan       Admin   East

In [8]:
?df1.merge

In [12]:
df1.merge(df2, left_on=['Zone', 'Person'], right_on=['Region', 'Person'])

    Zone  Person  Division_x Region  Division_y
0   West    Jack       Sales   West       Sales
1   West    Jill       Sales   West       Sales
2  North   Jason  Operations  North  Operations
3   East  Jordan       Admin   East       Admin

In [10]:
df1.merge(df2, on='Person')

    Zone  Person  Division_x Region  Division_y
0   West    Jack       Sales   West       Sales
1   West    Jill       Sales   West       Sales
2  North   Jason  Operations  North  Operations
3   East  Jordan       Admin   East       Admin

In [11]:
df1.merge(df2)

    Zone  Person    Division Region
0   West    Jack       Sales   West
1   West    Jill       Sales   West
2  North   Jason  Operations  North
3   East  Jordan       Admin   East

In [14]:
df1.merge(df2, how='right').merge()

    Zone   Person    Division   Region
0   West     Jack       Sales     West
1   West     Jill       Sales     West
2  North    Jason  Operations    North
3   East   Jordan       Admin     East
4    NaN  Jackson  Management     East
5    NaN     Adam       Admin  Midwest

In [15]:
df3 = df1.copy()

In [16]:
df3

    Zone  Person    Division
0   West    Jack       Sales
1  South    Jane   Marketing
2   West    Jill       Sales
3  North   Jason  Operations
4   East  Jordan       Admin
5  South   Jenna       Sales

In [17]:
pd.concat([df1, df3])

    Zone  Person    Division
0   West    Jack       Sales
1  South    Jane   Marketing
2   West    Jill       Sales
3  North   Jason  Operations
4   East  Jordan       Admin
5  South   Jenna       Sales
0   West    Jack       Sales
1  South    Jane   Marketing
2   West    Jill       Sales
3  North   Jason  Operations
4   East  Jordan       Admin
5  South   Jenna       Sales

In [ ]:
import os

csv_files = []

for file in os.lisdir():
    if file[:-4] == '.csv':
        csv_files.append(file)
        
dfs = [pd.read_csv(file) for file in csv_files]

df = pd.concat(dfs)

In [43]:
df = pd.read_excel('../data/superstore.xls')

In [20]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [21]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [44]:
df2 = pd.read_excel('../data/superstore.xls', sheet_name=1)
df3 = pd.read_excel('../data/superstore.xls', sheet_name=2)

In [28]:
df2.head()

  Returned        Order ID
0      Yes  CA-2017-153822
1      Yes  CA-2017-129707
2      Yes  CA-2014-152345
3      Yes  CA-2015-156440
4      Yes  US-2017-155999

In [25]:
df3.head()

              Person   Region
0      Anna Andreadi     West
1        Chuck Magee     East
2     Kelly Williams  Central
3  Cassandra Brandow    South

In [26]:
df2.shape

(296, 2)

In [45]:
df = df.merge(df2, on='Order ID', how='left')

In [32]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Returned
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,NaN
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,NaN
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,NaN
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,NaN
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,NaN

In [33]:
df3

              Person   Region
0      Anna Andreadi     West
1        Chuck Magee     East
2     Kelly Williams  Central
3  Cassandra Brandow    South

In [34]:
df['Region'].value_counts()

West       3203
East       2848
Central    2323
South      1620
Name: Region, dtype: int64

In [35]:
df['Region']

0         South
1         South
2          West
3         South
4         South
5          West
6          West
7          West
8          West
9          West
10         West
11         West
12        South
13         West
14      Central
15      Central
16      Central
17         West
18         West
19         West
20         West
21      Central
22      Central
23         East
24         West
25         West
26         West
27         East
28         East
29         East
         ...
9964       East
9965       East
9966       East
9967       East
9968       East
9969       East
9970      South
9971      South
9972    Central
9973       West
9974       West
9975       West
9976       West
9977       West
9978       West
9979       West
9980      South
9981       East
9982    Central
9983    Central
9984       East
9985       East
9986       West
9987      South
9988      South
9989      South
9990       West
9991       West
9992       West
9993       West
Name: Region, Length: 9994, dtype: object

In [46]:
df = df.merge(df3, how='left')

In [38]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Returned,Person
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,NaN,Cassandra Brandow
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,NaN,Cassandra Brandow
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,NaN,Anna Andreadi
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,NaN,Cassandra Brandow
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,NaN,Cassandra Brandow

In [47]:
df['Returned'].value_counts()

Yes    800
Name: Returned, dtype: int64

In [48]:
df['Returned'].fillna('No', inplace=True)

In [49]:
df['Returned'].value_counts()

No     9194
Yes     800
Name: Returned, dtype: int64

In [64]:
def find_nas(col):
    return pd.isnull(col).sum()

In [78]:
pd.isnull(df['Sales']).sum()

0

In [77]:
find_nas(df['Sales'])

0

In [65]:
df.groupby(['Region', 'Category'])['Sales'].agg(['mean', 'min', 'max', find_nas])

                               mean    min        max  find_nas
Region  Category
Central Furniture        340.534644  1.892   3504.900       0.0
        Office Supplies  117.458801  0.444   9892.740       0.0
        Technology       405.753124  1.980  17499.950       0.0
East    Furniture        346.574383  2.960   4416.174       0.0
        Office Supplies  120.044425  0.852   4663.736       0.0
        Technology       495.278469  2.970  11199.968       0.0
South   Furniture        353.309289  2.784   4297.644       0.0
        Office Supplies  126.282727  1.167   6354.950       0.0
        Technology       507.753952  1.584  22638.480       0.0
West    Furniture        357.302325  3.480   3610.848       0.0
        Office Supplies  116.422377  1.080   8187.650       0.0
        Technology       420.687533  0.990  13999.960       0.0

In [70]:
df.resample('W-Fri', on='Order Date')['Sales'].sum()

Order Date
2014-01-03       16.4480
2014-01-10     4897.2280
2014-01-17     4075.6090
2014-01-24     3188.5960
2014-01-31     2059.0140
2014-02-07     1422.8740
2014-02-14     2764.2540
2014-02-21      226.8320
2014-02-28      105.9320
2014-03-07     6388.5030
2014-03-14     3768.8200
2014-03-21    37610.3540
2014-03-28     3902.6170
2014-04-04     6308.4550
2014-04-11    11840.9480
2014-04-18     3905.0230
2014-04-25     5583.0060
2014-05-02     5184.7480
2014-05-09     4061.2970
2014-05-16     6219.9890
2014-05-23     6221.3680
2014-05-30     5865.8130
2014-06-06     9272.4270
2014-06-13     8751.7390
2014-06-20     7306.9576
2014-06-27     7605.6090
2014-07-04     3360.0870
2014-07-11     5939.5710
2014-07-18     2886.3720
2014-07-25    17011.4120
                 ...
2017-06-16    13711.9270
2017-06-23     9246.6715
2017-06-30    17908.9762
2017-07-07    10249.4080
2017-07-14     9846.8760
2017-07-21    12716.6840
2017-07-28     8978.7500
2017-08-04     6109.7660
2017-08-11     7939.1220
2017-08-18    25403.1920
2017-08-25    15918.3780
2017-09-01    12484.9380
2017-09-08    22670.8410
2017-09-15    24586.5560
2017-09-22    24558.2970
2017-09-29    14248.3880
2017-10-06    19645.9760
2017-10-13    19134.6690
2017-10-20     8867.9492
2017-10-27    25663.7450
2017-11-03    18758.0970
2017-11-10    28868.4280
2017-11-17    31203.9990
2017-11-24    20239.9480
2017-12-01    29713.8750
2017-12-08    26018.0330
2017-12-15    16953.4520
2017-12-22    18388.9940
2017-12-29    16423.8718
2018-01-05      713.7900
Freq: W-FRI, Name: Sales, Length: 210, dtype: float64

In [75]:
df.set_index('Order Date')

,Row ID,Order ID,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Returned,Person
Order Date,,,,,,,,,,,,,,,,,,,,,
2016-11-08,1,CA-2016-152156,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,No,Cassandra Brandow
2016-11-08,2,CA-2016-152156,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,No,Cassandra Brandow
2016-06-12,3,CA-2016-138688,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,No,Anna Andreadi
2015-10-11,4,US-2015-108966,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,No,Cassandra Brandow
2015-10-11,5,US-2015-108966,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,No,Cassandra Brandow
2014-06-09,6,CA-2014-115812,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,...,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694,No,Anna Andreadi
2014-06-09,7,CA-2014-115812,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,...,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656,No,Anna Andreadi
2014-06-09,8,CA-2014-115812,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,...,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152,No,Anna Andreadi
2014-06-09,9,CA-2014-115812,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,...,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825,No,Anna Andreadi
2014-06-09,10,CA-2014-115812,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,...,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700,No,Anna Andreadi
2014-06-09,11,CA-2014-115812,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,...,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092,No,Anna Andreadi
2014-06-09,12,CA-2014-115812,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,...,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,4,0.20,68.3568,No,Anna Andreadi
2017-04-15,13,CA-2017-114412,2017-04-20,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,...,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520,3,0.20,5.4432,No,Cassandra Brandow
2016-12-05,14,CA-2016-161389,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,Washington,...,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,3,0.20,132.5922,No,Anna Andreadi
2015-11-22,15,US-2015-118983,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,...,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580,No,Kelly Williams
2015-11-22,16,US-2015-118983,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,...,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3,0.80,-3.8160,No,Kelly Williams
2014-11-11,17,CA-2014-105893,2014-11-18,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,Wisconsin,...,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.8800,6,0.00,13.3176,No,Kelly Williams
2014-05-13,18,CA-2014-167164,2014-05-15,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,Utah,...,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.5000,2,0.00,9.9900,No,Anna Andreadi
2014-08-27,19,CA-2014-143336,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,...,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.5600,2,0.00,2.4824,Yes,Anna Andreadi
2014-08-27,20,CA-2014-143336,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,...,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800,3,0.20,16.0110,Yes,Anna Andreadi
2014-08-27,21,CA-2014-143336,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,...,OFF-BI-10002215,Office Supplies,Binders,"Wilson Jones Hanging View Binder, White, 1""",22.7200,4,0.20,7.3840,Yes,Anna Andreadi
2016-12-09,22,CA-2016-137330,2016-12-13,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,...,OFF-AR-10000246,Office Supplies,Art,Newell 318,19.4600,7,0.00,5.0596,No,Kelly Williams
2016-12-09,23,CA-2016-137330,2016-12-13,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,...,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.3400,7,0.00,15.6884,No,Kelly Williams
2017-07-16,24,US-2017-156909,2017-07-18,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,Pennsylvania,...,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,2,0.30,-1.0196,No,Chuck Magee
2015-09-25,25,CA-2015-106320,2015-09-30,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649,No,Anna Andreadi
2016-01-16,26,CA-2016-121755,2016-01-20,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,California,...,OFF-BI-10001634,Office Supplies,Binders,Wilson Jones Active Use Binders,11.6480,2,0.20,4.2224,No,Anna Andreadi
2016-01-16,27,CA-2016-121755,2016-01-20,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,California,...,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.5700,3,0.00,11.7741,No,Anna Andreadi
2015-09-17,28,US-2015-150630,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,...,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522,No,Chuck Magee
2015-09-17,29,US-2015-150630,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,...,OFF-BI-10000474,Office Supplies,Binders,Avery Recycled Flexi-View Covers for Binding S...,9.6180,2,0.70,-7.0532,No,Chuck Magee
2015-09-17,30,US-2015-150630,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,...,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.2000,3,0.20,15.5250,No,Chuck Magee
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-05,9965,CA-2016-146374,2016-12-10,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,Delaware,...,FUR-FU-10002671,Furniture,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,13.4000,1,0.00,6.4320,No,Chuck Magee
2016-12-05,9966,CA-2016-146374,2016-12-10,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,Delaware,...,OFF-PA-10000349,Office Supplies,Paper,Easy-staple paper,4.9800,1,0.00,2.3406,No,Chuck Magee
2016-12-05,9967,CA-2016-146374,2016-12-10,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,Delaware,...,OFF-EN-10004483,Office Supplies,Envelopes,"#10 White Business Envelopes,4 1/8 x 9 1/2",109.6900,7,0.00,51.5543,No,Chuck Magee
2017-12-11,9968,CA-2017-153871,2017-12-17,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Plainfield,New Jersey,...,OFF-BI-10004209,Office Supplies,Binders,"Fellowes Twister Kit, Gray/Clear, 3/pkg",40.2000,5,0.00,18.0900,No,Chuck Magee
2017-12-11,9969,CA-2017-153871,2017-12-17,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Plainfield,New Jersey,...,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,735.9800,2,0.00,331.1910,No,Chuck Magee
2017-12-11,9970,CA-2017-153871,2017-12-17,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Plainfield,New Jersey,...,OFF-AP-10003622,Office Supplies,Appliances,"Bravo II Megaboss 12-Amp Hard Body Upright, Re...",22.7500,7,0.00,6.5975,No,Chuck Magee
2015-06-28,9971,CA-2015-103772,2015-07-02,Standard Class,MP-17470,Mark Packer,Home Office,United States,Smyrna,Georgia,...,OFF-BI-10002867,Office Supplies,Binders,GBC Recycled Regency Composition Covers,119.5600,2,0.00,54.9976,No,Cassandra Brandow
2015-06-28,9972,CA-2015-103772,2015-07-02,Standard Class,MP-17470,Mark Packer,Home Office,United States,Smyrna,Georgia,...,OFF-AR-10000538,Office Supplies,Art,"Boston Model 1800 Electric Pencil Sharpener, Gray",140.7500,5,0.00,42.2250,No,Cassandra Brandow
2016-09-11,9973,CA-2016-130225,2016-09-17,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Houston,Texas,...,OFF-EN-10000056,Office Supplies,Envelopes,Cameo Buff Policy Envelopes,99.5680,2,0.20,33.6042,No,Kelly Williams
2016-12-06,9974,US-2016-103674,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,California,...,TEC-PH-10004080,Technology,Phones,Avaya 5410 Digital phone,271.9600,5,0.20,27.1960,No,Anna Andreadi
2016-12-06,9975,US-2016-103674,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,California,...,OFF-AR-10004752,Office Supplies,Art,Blackstonian Pencils,18.6900,7,0.00,5.2332,No,Anna Andreadi
2016-12-06,9976,US-2016-103674,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,California,...,OFF-PA-10000743,Office Supplies,Paper,Xerox 1977,13.3600,2,0.00,6.4128,No,Anna Andreadi
2016-12-06,9977,US-2016-103674,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,California,...,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.5840,2,0.20,31.1980,No,Anna Andreadi
2016-12-06,9978,US-2016-103674,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,California,...,OFF-FA-10003467,Office Supplies,Fasteners,"Alliance Big Bands Rubber Bands, 12/Pack",13.8600,7,0.00,0.0000,No,Anna Andreadi
2016-12-06,9979,US-2016-103674,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,California,...,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,13.3760,4,0.20,4.6816,No,Anna Andreadi
2016-12-06,9980,US-2016-103674,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,California,...,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152,No,Anna Andreadi
2015-09-06,9981,US-2015-151435,2015-09-09,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,Louisiana,...,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548,No,Cassandra Brandow
2017-08-03,9982,CA-2017-163566,2017-08-06,First Class,TB-21055,Ted Butterfield,Consumer,United States,Fairfield,Ohio,...,OFF-LA-10004484,Office Supplies,Labels,Avery 476,16.5200,5,0.20,5.3690,No,Chuck Magee
2016-09-22,9983,US-2016-157728,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,Michigan,...,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.5600,7,0.00,16.7132,No,Kelly Williams
2016-09-22,9984,US-2016-157728,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,Michigan,...,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.9800,2,0.00,27.4344,No,Kelly Williams
2015-05-17,9985,CA-2015-100251,2015-05-23,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,New York,...,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.5000,10,0.00,15.1200,No,Chuck Magee
2015-05-17,9986,CA-2015-100251,2015-05-23,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,New York,...,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.6000,4,0.00,16.1240,No,Chuck Magee
2016-09-29,9987,CA-2016-125794,2016-10-03,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,California,...,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.2400,1,0.00,15.2208,No,Anna Andreadi
2017-11-17,9988,CA-2017-163629,2017-11-21,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,Georgia,...,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.9900,1,0.00,28.7964,No,Cassandra Brandow
2017-11-17,9989,CA-2017-163629,2017-11-21,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,Georgia,...,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470,No,Cassandra Brandow
2014-01-21,9990,CA-2014-110422,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,...,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,No,Cassandra Brandow
2017-02-26,9991,CA-2017-121258,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,...,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,Yes,Anna Andreadi
2017-02-26,9992,CA-2017-121258,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,...,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,Yes,Anna Andreadi
2017-02-26,9993,CA-2017-121258,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,...,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,Yes,Anna Andreadi
2017-05-04,9994,CA-2017-119914,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,...,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,No,Anna Andreadi